### PR TITLE
Add logs to snakemake rules

### PR DESCRIPTION
**Pull request by jashapiro**
**Issue Addressed**
N/A

**What is the purpose of these changes?**

This PR adds `log:` directives to the Snakefiles in this repository. I originally was prompted to do this because I rand `snakemake --lint` as an thought for testing, and saw that this was recommended, and it comes with a few advantages: it should make debugging rules a bit easier, as the logs are now written to files rather than just the screen, and this also means that the screen output is _only_ snakemake rules, which saves a bit of random text & prevents multiple jobs from writing to the screen at once.

**What changes did you make?**
The primary change is adding the `log:` directive to all rules, which will store files in the `logs/` directory, arranged similarly to the input data. The log file path has to include all wildcards, hence the nested directory structure. I could alternatively have made very long names for the log files, but I thought nesting was just as easy. Happy to reconsider this though.

Each rule also adds a line for outputting stdout and stderr to the log file, usually in the form `&> {log}`.

I also did some cleanup removing no longer needed references to `{workflow.basedir}` and `.Rprofile` as those should now be covered by always running the workflows from the main project directory. 

**Were there any other solutions that you tried?**
Not really: just whether to change the output paths, but doing it another way would mean breaking up some of the `{basedir}` wildcards, which seemed like trouble.

**Any comments, concerns, or questions important for reviewers**

`snakemake --lint` also complains about using the config settings directly in shell commands. It would prefer that they be defined as `params` and used that way. I decided not to do that here, as it adds a lot of boilerplate, and doesn't give as obvious a benefit for debugging/cleaner screens.

Info about logs should probably be added to the docs, but I don't think great detail is needed.

**Checklist**

Place an `x` in all boxes that you have completed.

- [x] I have run the most recent version of the code
- [ ] If I am adding in reports or generating any plots, I have reviewed the necessary reports
- [ ] I have added all necessary documentation (if applicable)

### CODE REVIEW

**Review by cbethell — COMMENTED** [review]
Great idea to include the logs here @jashapiro, thanks!

I now encounter a pandoc error when I attempt to run the snakefile with the changes in this PR however. Do you think this is possibly due to some pandoc update?

Screen Shot 2022-09-23 at 9 58 52 AM

**Comment by jashapiro** [comment]
That is a conda error, which should not be related to any changes that I made in this PR. We pinned the pandoc version a few revisions ago because of a bug in one of the later version of pandoc, but I am not sure why it thinks it can't download it here.

**Comment by jashapiro** [comment]
Jus to check I just rebuilt my environments in the `scpca-downstream-analysis` project with `./setup_envs.sh`, and everything seemed to install correctly. I'm not sure why your conda might not have been able to find pandoc 2.18.

**Comment by jashapiro** [comment]
Ah, looking at https://anaconda.org/conda-forge/pandoc/files, it seems like for some reason the `osx-arm64` builds of pandoc don't exist, except for version 2.19. Which makes me think that snakemake is trying to rebuild the environment because something may have changed since the last time your ran the workflow, but it is failing because it is not using the Intel build environment. Rerunning `setup_envs.sh` _should_ solve the problem.

**Comment by cbethell** [comment]
> 

Unfortunately I am still getting the pandoc error linked in https://github.com/AlexsLemonade/scpca-downstream-analyses/pull/222#pullrequestreview-1118636195, but this now convinces me that it is indeed some `osx-arm64` error.

**Comment by jashapiro** [comment]
> > Ah, looking at https://anaconda.org/conda-forge/pandoc/files, it seems like for some reason the osx-arm64 builds of pandoc don't exist, except for version 2.19. Which makes me think that snakemake is trying to rebuild the environment because something may have changed since the last time your ran the workflow, but it is failing because it is not using the Intel build environment. Rerunning setup_envs.sh should solve the problem.
> 
> Unfortunately I am still getting the pandoc error linked in [#222 (review)](https://github.com/AlexsLemonade/scpca-downstream-analyses/pull/222#pullrequestreview-1118636195), but this now convinces me that it is indeed some `osx-arm64` error.

Can you try deleting the `.snakemake/conda` directory and rerunning `setup_envs.sh`? If it is working correctly, you should not be creating any `osx-arm64` environments. If it doesn't work, ping me on Slack so we can do some debugging. We'd really like to keep pandoc pinned if we can.

**Review by cbethell — APPROVED** [review]
> Can you try deleting the .snakemake/conda directory and rerunning setup_envs.sh? If it is working correctly, you should not be creating any osx-arm64 environments. If it doesn't work, ping me on Slack so we can do some debugging. We'd really like to keep pandoc pinned if we can.

As we discovered this morning, the issue is solved by running things on my local Mac terminal rather than RStudio terminal (as you noted @jashapiro, RStudio needs to complete the Electron transition before the `setup_envs.sh` script can work as expected there).

That said I am going to approve this PR now that I can confirm things work here ✅

**Pull request merged**
